# Generated by Django 2.2.13 on 2020-06-23 14:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('term', models.IntegerField()),
                ('education_format', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Part-time-express', 'Part-time-express')], default='Full-time', max_length=20)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Faculty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('teaching_subject', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('type', models.CharField(choices=[('End-of-term-test', 'End-of-term-test'), ('Test', 'Test'), ('Exam', 'Exam'), ('Lecture', 'Lecture'), ('Practice', 'Practice')], default='Lecture', max_length=20)),
                ('schedule_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.ScheduleDay')),
                ('sub_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_sub_teacher', to='home.Teacher')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_teacher', to='home.Teacher')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scheduleitem',
            constraint=models.UniqueConstraint(fields=('start_time', 'schedule_day'), name='start_time_schedule_day'),
        ),
        migrations.AddConstraint(
            model_name='scheduleitem',
            constraint=models.UniqueConstraint(fields=('end_time', 'schedule_day'), name='end_time_schedule_day'),
        ),
        migrations.AddConstraint(
            model_name='scheduleitem',
            constraint=models.UniqueConstraint(fields=('title', 'start_time', 'schedule_day', 'teacher'), name='title_start_time_schedule_day_teacher'),
        ),
        migrations.AddConstraint(
            model_name='scheduleitem',
            constraint=models.UniqueConstraint(fields=('title', 'end_time', 'schedule_day', 'teacher'), name='title_end_time_schedule_day_teacher'),
        ),
    ]
